# ---------------------------------------------------------------------------- #
#               _____                                _                         #
#              (____ \                              | |                        #
#               _   \ \ _   _  ___   ___  ____ _   _| |  _ ____                #
#              | |   | | | | |/ _ \ /___)/ _  ) | | | | / ) _  |               #
#              | |__/ /| |_| | |_| |___ ( (/ / \ V /| |< ( ( | |               #
#              |_____/  \__  |\___/(___/ \____) \_/ |_| \_)_||_|               #
#                      (____/                                                  #
#                                                                              #
#                                                                              #
#      configuration for the dyosevka font, built using be5invis/iosevka.      #
#                                                                              #
# ---------------------------------------------------------------------------- #

[buildPlans.Dyosevka]
family   = "Dyosevka"
spacing  = "term"
serifs   = "sans"
no-cv-ss = false

[buildPlans.Dyosevka.variants.design]
capital-a = "curly-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifed"
capital-k = "straight"
capital-n = "standard"
capital-p = "closed"
capital-q = "curly-tailed"
capital-r = "curly"
capital-s = "serifless"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifed-with-crossbar"
a = "single-storey"
b = "toothless-rounded"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
i = "tailed"
j = "serifless"
k = "curly"
l = "tailed"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-rounded"
t = "standard"
u = "toothless-rounded"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "cursive"
z = "curly-serifless"
ampersand      = "et-toothed"
asterisk       = "low"
at             = "short"
bar            = "natural-slope"
brace          = "curly"
caret          = "low"
dollar         = "open-cap"
eight          = "crossing-asymmetric"
five           = "oblique-upper-left-bar"
latn-epsilon   = "serifless"
lig-ltgteq     = "slanted"
lower-alpha    = "crossing"
lower-lambda   = "curly"
nine           = "open-contour"
number-sign    = "upright"
paragraph-sign = "low"
paren          = "large-contour"
question       = "corner-flat-hooked"
seven          = "curly-serifed"
six            = "open-contour"
turn-v         = "curly"
two            = "curly-neck"
zero           = "dotted"
